### ISSUE TITLE
Add discussion to docs of using umami with packages that are not terrainbento or Landlab. 

### ISSUE THREAD

**Issue by kbarnhart** [TerrainBento/umami#8]
In his [joss review](https://github.com/openjournals/joss-reviews/issues/1776) @tristian-salles recommends 

> Potentially the authors can also provide in their readthedocs documentation an additional page on the required steps to use it with other packages than terrainbento and the Landlab Toolkit...

Will do.

**Comment by kbarnhart** [comment]
@tristian-salles, I made a new tutorial to address this issue [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/TerrainBento/umami/master?filepath=notebooks%2FOtherIO_options.ipynb)

If you have any comments on the tutorial, I'd welcome incorporating them before I close the issue. 

Thanks!

**Comment by tristan-salles** [comment]
Hi @kbarnhart, sorry didn't see the issue before. This looks really good well done!

**Comment by kbarnhart** [comment]
Thanks @tristan-salles. Closing.
